---
site_name: "biostride"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
  - Background:
    - Overview: background/index.md
    - NEXUS: background/nexus.md
    - mmCIF: background/mmcif.md
    - EMPIAR: background/empiar.md
    - EMDB: background/emdb.md
    - DIALS: background/dials.md
    - SASDB: background/sasdb.md
    - Data Lakehouse Strategy: background/biostride-data-lakehouse-strategy.md
    - Integration with BER: background/ber-doe-facilities.md
site_url: https://cmungall.github.io/biostride
repo_url: https://github.com/cmungall/biostride
